### ISSUE TITLE
uninitialized constant Hash::URI

### ISSUE THREAD

**Issue by jmervine** [MaxCDN/ruby-maxcdn#11]
While we were testing one of the features via API we've found that ruby SDK is acting up in a way that it errors out for Hash::URI not being initialized when called under _escape but, not sure I can back trace properly:

#### call:

```ruby
require 'maxcdn' 
api = MaxCDN::Client.new("ALIAS", "SECRET", "KEY")
params = {'canonical_link_headers' => '1'} 
api.put('/zones/pull.json/ZONE', params)
```

#### exception:

```
$ ruby maxcdn.rb       
/home/user/.gem/ruby/gems/maxcdn-0.3.0/lib/ext/hash.rb:5:in `_escape': uninitialized constant
Hash::URI (NameError) 
       from /home/user/.gem/ruby/gems/maxcdn-0.3.0/lib/ext/hash.rb:20:in `block in to_params
' 
       from /home/user/.gem/ruby/gems/maxcdn-0.3.0/lib/ext/hash.rb:14:in `each' 
       from /home/user/.gem/ruby/gems/maxcdn-0.3.0/lib/ext/hash.rb:14:in `to_params' 
       from /home/user/.gem/ruby/gems/maxcdn-0.3.0/lib/maxcdn.rb:46:in `_response_as_json' 
       from /home/user/.gem/ruby/gems/maxcdn-0.3.0/lib/maxcdn.rb:90:in `block (2 levels) in 
<class:Client>' 
       from maxcdn.rb:11:in `<main>'
```

**Comment by jmervine** [comment]
Quick fix:

```ruby
require 'uri' # << add this here
require 'maxcdn' 
api = MaxCDN::Client.new("ALIAS", "SECRET", "KEY")
params = {'canonical_link_headers' => '1'} 
api.put('/zones/pull.json/ZONE', params)
```

**Comment by obsidianspork** [comment]
I raised this issue through the support channel last Friday and I was able to successfully update the parameters I submit though API.get, great job!

**Comment by jmervine** [comment]
Fixes release: https://rubygems.org/gems/maxcdn/versions/0.3.1
